# Generated by Django 3.2.3 on 2021-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('rno', models.IntegerField(max_length=64)),
                ('fname', models.CharField(max_length=64)),
                ('lname', models.CharField(max_length=64)),
                ('present', models.BooleanField()),
                ('aruco_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
