# Generated by Django 3.2.3 on 2021-06-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='rno',
            field=models.IntegerField(),
        ),
    ]
